### ISSUE TITLE
Essentials-S Homepage Lists "Homes" as a Feature, but No Commands Found in Wiki or Game

### ISSUE THREAD

**Issue by narnacle** [EssentialsS/Implementation#6]
### Describe feature

**Bug Summary:**
The homepage of the Essentials-S plugin states that the plugin currently supports "homes." However, there is no documentation or commands related to "homes" available on the official wiki, and attempts to use "homes" commands in the game have been unsuccessful.

**Steps to Reproduce:**
1. Visit the Essentials-S homepage.
2. Note the statement indicating that "homes" is a working feature.
3. Search the official wiki for any documentation or commands related to "homes."
4. Attempt to use common "homes" commands (e.g., /sethome, /home) in the game.

**Expected Result:**
Documentation and commands related to "homes" should be available on the wiki and functional in the game.

**Actual Result:**
No documentation or commands related to "homes" are found on the wiki, and attempting to use "homes" commands in the game yields no results.

**Additional Information:**
- URL of the homepage with the statement: [Essentials-S Homepage](https://ore.spongepowered.org/MoseMister/Essentials-S/versions)
- Version of Essentials-S plugin being used: 0.0.8
- Server type and version: Forge 1.16.5 - 36.2.34 with SpongeForge 1.16.5-36.2.5-8.2.1-RC1587

Please clarify if "homes" are supported in the current version of the plugin and, if so, provide the necessary documentation or commands. If "homes" are not currently supported, consider updating the homepage to reflect the accurate feature set.

**Comment by mosemister** [comment]
This was for version 0.9 which was fully written, but then a windows update happened which corrupted all my files. Which broke the camels back for motivation on this project (the other being the release of ``CommandPack``)

Now ive taken a long break from the project, i can probably get back into it and finish it for 1.16.5

**Comment by mosemister** [comment]
Uploaded version 0.0.9 that includes a homes command. Wiki will come shortly

**Comment by mosemister** [comment]
Updated wiki
